Fix forgotten renamed fields
Author `url` field had been renamed to `profile_url` but "url" name was still being used in AuthorSerializer's `field`.
This would lead to (misleading) error bellow during tests:

    AssertionError: `HyperlinkedIdentityField` requires the request in the serializer context. Add `context={'request': request}` when instantiating the serializer.